# Generated by Django 5.2.8 on 2025-12-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="services.serviceschedule",
            ),
        ),
    ]
