# Generated by Django 5.2.8 on 2025-11-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0002_vehicle_photo_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Human-readable address", max_length=500
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, help_text="e.g., 'Mall parking lot'", max_length=200
                    ),
                ),
                (
                    "photos",
                    models.JSONField(default=list, help_text="List of photo URLs"),
                ),
                ("notes", models.TextField(blank=True)),
                ("parked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "timer_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When parking meter expires", null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Is this the current parking spot?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_spots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_spots",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-parked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-parked_at"],
                        name="parking_par_user_id_76e2bc_idx",
                    ),
                    models.Index(
                        fields=["active"], name="parking_par_active_b1d12a_idx"
                    ),
                ],
            },
        ),
    ]
