# Generated by Django 5.2.8 on 2025-11-28 08:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("terms", models.TextField(blank=True, null=True)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                ("eligible_memberships", models.JSONField(blank=True, default=list)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "offers",
            },
        ),
    ]
