# Generated by Django 5.2.8 on 2025-11-30 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0002_vehicle_photo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate Attention"),
                            ("soon", "Address Soon"),
                            ("routine", "Routine Maintenance"),
                            ("preventive", "Preventive Care"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_recommendations",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.IntegerField(
                        default=100, help_text="Overall health score 0-100"
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("engine_score", models.IntegerField(default=100)),
                ("transmission_score", models.IntegerField(default=100)),
                ("brakes_score", models.IntegerField(default=100)),
                ("tires_score", models.IntegerField(default=100)),
                ("battery_score", models.IntegerField(default=100)),
                ("fluids_score", models.IntegerField(default=100)),
                ("last_diagnostic_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_diagnostic_odometer",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "diagnostics",
                    models.JSONField(
                        default=dict, help_text="Detailed diagnostic data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_status",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticTroubleCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text="e.g., P0301", max_length=10)),
                ("description", models.TextField()),
                (
                    "system",
                    models.CharField(
                        blank=True, help_text="Affected system", max_length=50
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "freeze_frame_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Freeze frame data when code was set",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dtc_codes",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-detected_at"],
                        name="vehicle_hea_vehicle_0b2541_idx",
                    ),
                    models.Index(
                        fields=["active"], name="vehicle_hea_active_4295eb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("engine", "Engine"),
                            ("transmission", "Transmission"),
                            ("brakes", "Brakes"),
                            ("tires", "Tires"),
                            ("battery", "Battery"),
                            ("fluids", "Fluids"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_alerts",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-created_at"],
                        name="vehicle_hea_vehicle_30d680_idx",
                    ),
                    models.Index(
                        fields=["resolved"], name="vehicle_hea_resolve_bcf7b8_idx"
                    ),
                ],
            },
        ),
    ]
